"""
clusterer.py — KMeans clustering with silhouette-based auto-k selection.

Design decisions:
- KMeans chosen over HDBSCAN for interpretability at this signal volume.
  At <500 signals, KMeans produces stable, explainable clusters.
  HDBSCAN is on the v1.2 roadmap for noise-robust production clustering.
- Auto-k range: 3 to min(10, n_signals // 5) to avoid over-fragmentation.
- Cluster labels generated by GPT-4o from 5 representative signal samples.
"""

import os
import numpy as np
from typing import List, Tuple, Dict
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import normalize
from openai import AsyncOpenAI

client = AsyncOpenAI(api_key=os.getenv("OPENAI_API_KEY"))


def find_optimal_k(embeddings: np.ndarray, min_k: int = 3, max_k: int = 10) -> int:
    """
    Find the optimal number of clusters using silhouette score.

    Silhouette score measures how well each point fits its own cluster
    vs neighboring clusters. Higher is better (-1 to 1 range).
    We choose k that maximizes silhouette score.

    Args:
        embeddings: Normalized embedding matrix (n_samples, n_dims)
        min_k: Minimum clusters to consider
        max_k: Maximum clusters to consider

    Returns:
        Optimal k value
    """
    n_samples = len(embeddings)
    max_k = min(max_k, n_samples // 3)  # Need at least 3 samples per cluster
    max_k = max(max_k, min_k)

    if n_samples < min_k * 3:
        return min_k  # Not enough data to meaningfully cluster

    best_k = min_k
    best_score = -1.0

    for k in range(min_k, max_k + 1):
        km = KMeans(n_clusters=k, random_state=42, n_init=10)
        labels = km.fit_predict(embeddings)

        if len(set(labels)) < k:
            continue  # Some clusters are empty; skip this k

        score = silhouette_score(embeddings, labels, sample_size=min(500, n_samples))
        if score > best_score:
            best_score = score
            best_k = k

    return best_k


def cluster_embeddings(embeddings: np.ndarray, k: int) -> Tuple[np.ndarray, np.ndarray]:
    """
    Run KMeans and return (labels, centroids).

    Args:
        embeddings: Normalized embedding matrix
        k: Number of clusters

    Returns:
        (labels array, centroids array)
    """
    km = KMeans(n_clusters=k, random_state=42, n_init=10)
    labels = km.fit_predict(embeddings)
    return labels, km.cluster_centers_


def get_representative_signals(
    signals: List[str],
    labels: np.ndarray,
    cluster_idx: int,
    n: int = 5
) -> List[str]:
    """
    Get the n signals closest to the cluster centroid.
    These are used to generate the GPT-4o cluster label.
    """
    cluster_mask = labels == cluster_idx
    cluster_signals = [s for s, m in zip(signals, cluster_mask) if m]
    return cluster_signals[:n]


async def generate_cluster_label(representative_signals: List[str]) -> str:
    """
    Use GPT-4o to generate a concise, descriptive theme label for a cluster.

    The label should be 3-6 words, specific enough to be actionable,
    and not generic like "user feedback" or "product issues".
    """
    signal_text = "\n".join(f"- {s[:200]}" for s in representative_signals[:5])

    prompt = f"""You are a product manager analyzing customer feedback clusters.

Here are {len(representative_signals)} representative signals from one cluster:

{signal_text}

Generate a concise theme label (3-6 words) that captures the core product problem or request these signals share.
Be specific and actionable, not generic. Examples of good labels: "Slow report export performance", "Missing Slack notification integration", "Confusing onboarding flow".

Respond with ONLY the label text, nothing else."""

    response = await client.chat.completions.create(
        model="gpt-4o",
        messages=[{"role": "user", "content": prompt}],
        max_tokens=30,
        temperature=0.3,
    )
    return response.choices[0].message.content.strip().strip('"').strip("'")


async def cluster_and_label(
    embeddings: List[List[float]],
    signals: List[str],
) -> List[Dict]:
    """
    Main clustering pipeline: normalize -> auto-k -> KMeans -> label each cluster.

    Args:
        embeddings: List of embedding vectors (one per signal)
        signals: Corresponding list of signal text strings

    Returns:
        List of dicts with cluster_index, label, signal_indices
    """
    emb_matrix = np.array(embeddings)
    normalized = normalize(emb_matrix)  # Cosine similarity works better on normalized embeddings

    k = find_optimal_k(normalized)
    labels, _ = cluster_embeddings(normalized, k)

    cluster_results = []
    for cluster_idx in range(k):
        rep_signals = get_representative_signals(signals, labels, cluster_idx)
        label = await generate_cluster_label(rep_signals)
        signal_indices = [i for i, l in enumerate(labels) if l == cluster_idx]

        cluster_results.append({
            "cluster_index": cluster_idx,
            "label": label,
            "signal_indices": signal_indices,
        })

    return cluster_results, labels.tolist()
